# Nome do Projeto
spring.application.name=mediaflow


spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Configurações da API TMDB
tmdb.api.key=29584d87801f565bf1439967617e34ca
tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyOTU4NGQ4NzgwMWY1NjViZjE0Mzk5Njc2MTdlMzRjYSIsIm5iZiI6MTc3NzA1MjE5OC42OTgsInN1YiI6IjY5ZWJhYTI2NDFkMDhlNDkyZjZiMTAwZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.AuCb4GcKxR5N42kxwkWi6t_RoKFFvIEiPvJmg3YnG7A
tmdb.api.base-url=https://api.themoviedb.org/3

# Porta do Servidor
server.port=8080